[all:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_user=ansible

[layer3:children]
ios
nxos

[ios]
unwe_ul01 ansible_host=10.40.4.1

[ios:vars]
ansible_become=yes
ansible_become_method=enable
ansible_network_os=cisco.ios.ios
ansible_user=jooseeF00t
ansible_password=Fa86*@mc21

[nxos]
libr01 ansible_host=10.2.4.1

[nxos:vars]
ansible_become=yes
ansible_become_method=enable
ansible_network_os=cisco.nxos.nxos
ansible_user=jooseeF00t
ansible_password=Fa86*@mc21
