[all:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_user=ansible

[layer3:children]
ios
nxos

[ios]
unwe_ul01 ansible_host=IP

[ios:vars]
ansible_become=yes
ansible_become_method=enable
ansible_network_os=cisco.ios.ios
ansible_user=USER
ansible_password=PASS

[nxos]
libr01 ansible_host=IP

[nxos:vars]
ansible_become=yes
ansible_become_method=enable
ansible_network_os=cisco.nxos.nxos
ansible_user=USER
ansible_password=PASS
